version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mybank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mybank
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.2-fpm
    container_name: mybank-php
    volumes:
      - .:/var/www/html

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybank-symfony
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  db_data:
